name: icount_segment
description: Formats a GTF file for use with iCount sigxls
keywords:
  - iCLIP
tools:
  - icount:
      description: Computational pipeline for analysis of iCLIP data
      homepage: None
      documentation: None
      tool_dev_url: None
      doi: ""
      licence: ["MIT"]

input:
  - gtf:
      type: file
      description: A GTF file to use for the segmentation
      pattern: "*.{gtf}"
  - fai:
      type: file
      description: FAI file corresponding to the reference sequence
      pattern: "*.{fai}"

output:
  - gtf:
      type: file
      description: Segmented GTF file for use with iCount sigxls
      pattern: "*.{gtf}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@marc-jones"
  - "@chris-cheshire"
