name: icount_sigxls
description: Runs iCount peaks on a BED file of crosslinks
keywords:
  - iCLIP
tools:
  - icount:
      description: Computational pipeline for analysis of iCLIP data
      homepage: None
      documentation: None
      tool_dev_url: None
      doi: ""
      licence: ["MIT"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bed:
      type: file
      description: BED file of crosslinks
      pattern: "*.{bam,bam.gz}"
  - segmentation:
      type: file
      description: A iCount segmentation file
      pattern: "*.{gtf}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - peaks:
      type: file
      description: Crosslinks deemed significant by iCount
      pattern: "*.{bed.gz}"
  - scores:
      type: file
      description: Crosslink scores calculated by iCount
      pattern: "*.{tsv}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@marc-jones"
  - "@chris-cheshire"
